#requires -Version 5.1
<#
.SYNOPSIS
    Codex / Claude Usage Watcher — one-line installer for Windows.

.DESCRIPTION
    irm https://raw.githubusercontent.com/jbss6888hn-tech/usage-watcher/main/install.ps1 | iex

    Installs Node + gh CLI (via winget if missing), clones the daemon repo,
    creates a private GitHub gist, registers the daemon and tray PowerShell
    script as logon Scheduled Tasks, and prints a QR for iPhone Scriptable setup.
#>

$ErrorActionPreference = "Stop"

$RepoUrl     = if ($env:USAGE_WATCHER_REPO) { $env:USAGE_WATCHER_REPO } else { "https://github.com/jbss6888hn-tech/usage-watcher.git" }
$InstallDir  = if ($env:USAGE_WATCHER_DIR)  { $env:USAGE_WATCHER_DIR  } else { Join-Path $env:USERPROFILE ".usage-watcher" }
$ConfigDir   = Join-Path $env:USERPROFILE ".config\usage-watcher"

function Step($msg) { Write-Host "▸ $msg" -ForegroundColor Cyan }
function OK($msg)   { Write-Host "✓ $msg" -ForegroundColor Green }
function Warn($msg) { Write-Host "! $msg" -ForegroundColor Yellow }
function Die($msg)  { Write-Host "✗ $msg" -ForegroundColor Red; exit 1 }

function Need-Cmd($name, $wingetId) {
    if (Get-Command $name -ErrorAction SilentlyContinue) { return }
    if (-not (Get-Command winget -ErrorAction SilentlyContinue)) {
        Die "$name not found and winget not available. Install $name manually first."
    }
    Step "Installing $name via winget…"
    winget install --id $wingetId -e --accept-package-agreements --accept-source-agreements | Out-Null
    # Refresh PATH
    $env:Path = [System.Environment]::GetEnvironmentVariable("Path", "Machine") + ";" +
                [System.Environment]::GetEnvironmentVariable("Path", "User")
}

# --- 1. Prerequisites ---------------------------------------------------------
Need-Cmd "node" "OpenJS.NodeJS"
Need-Cmd "git"  "Git.Git"
Need-Cmd "gh"   "GitHub.cli"
OK "Node $(node --version), gh present"

# --- 2. GitHub auth -----------------------------------------------------------
$ghStatus = & gh auth status -h github.com 2>&1
if ($LASTEXITCODE -ne 0) {
    Step "GitHub login (browser will open — pick 'gist' scope)"
    & gh auth login -h github.com -p https -s gist -w
}
$ghToken = (& gh auth token).Trim()
if (-not $ghToken) { Die "gh auth token returned empty" }
OK "GitHub authenticated"

# --- 3. Clone / pull repo -----------------------------------------------------
if (Test-Path "$InstallDir\.git") {
    Step "Updating $InstallDir…"
    git -C $InstallDir pull --ff-only | Out-Null
} elseif (Test-Path $InstallDir) {
    Warn "$InstallDir exists but isn't a git repo. Backing up and re-cloning."
    Rename-Item $InstallDir "$InstallDir.bak.$(Get-Date -UFormat %s)"
    git clone $RepoUrl $InstallDir | Out-Null
} else {
    Step "Cloning $RepoUrl → $InstallDir…"
    git clone $RepoUrl $InstallDir | Out-Null
}
Push-Location $InstallDir
& npm install --omit=dev --silent
Pop-Location
OK "Repo at $InstallDir (zero npm deps — fast install)"

# --- 4. Create/reuse private gist --------------------------------------------
New-Item -ItemType Directory -Force -Path $ConfigDir | Out-Null

$gistId = ""
$envPath = Join-Path $ConfigDir ".env"
if (Test-Path $envPath) {
    $line = Select-String -Path $envPath -Pattern "^GIST_ID=" | Select-Object -First 1
    if ($line) { $gistId = ($line.Line -replace "^GIST_ID=", "").Trim('"',' ') }
}

if (-not $gistId) {
    Step "Creating new private gist…"
    $tmpDir = New-Item -ItemType Directory -Path (Join-Path $env:TEMP "usage-watcher-init-$([System.IO.Path]::GetRandomFileName())")
    Set-Content (Join-Path $tmpDir "mac.json") '{"placeholder": true}'
    Set-Content (Join-Path $tmpDir "win.json") '{"placeholder": true}'
    $gistOut = & gh gist create (Join-Path $tmpDir "mac.json") (Join-Path $tmpDir "win.json") `
                  --desc "Codex/Claude usage snapshot (private — by usage-watcher)" 2>&1
    Remove-Item $tmpDir -Recurse -Force
    $gistLine = $gistOut | Select-Object -Last 1
    if ($gistLine -match "/([a-f0-9]+)$") { $gistId = $matches[1] } else { Die "could not parse gist id from: $gistOut" }
    OK "Gist created: $gistLine"
} else {
    OK "Reusing existing gist: $gistId"
}

# --- 5. Write .env ------------------------------------------------------------
@(
    "# Auto-generated by usage-watcher install.ps1 on $(Get-Date)"
    "GIST_ID=$gistId"
    "GITHUB_TOKEN=$ghToken"
    "HOST=win"
    "INTERVAL_SECONDS=60"
) | Set-Content -Path $envPath -Encoding UTF8

# Lock down the .env to current user
icacls $envPath /inheritance:r /grant:r "$($env:USERNAME):F" /grant:r "SYSTEM:F" | Out-Null
OK ".env written to $envPath"

# --- 6. Register Scheduled Tasks (daemon + tray) -----------------------------
$nodeExe   = (Get-Command node).Source
$pwshExe   = (Get-Command powershell.exe).Source
$daemonArgs = "$InstallDir\src\index.js"
$trayArgs   = "-NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File `"$InstallDir\windows\tray.ps1`""

# Unregister old tasks (if re-running installer)
Unregister-ScheduledTask -TaskName "UsageWatcherDaemon" -Confirm:$false -ErrorAction SilentlyContinue
Unregister-ScheduledTask -TaskName "UsageWatcherTray"   -Confirm:$false -ErrorAction SilentlyContinue

$daemonAction = New-ScheduledTaskAction -Execute $nodeExe -Argument $daemonArgs -WorkingDirectory $InstallDir
$trayAction   = New-ScheduledTaskAction -Execute $pwshExe -Argument $trayArgs

$logonTrigger = New-ScheduledTaskTrigger -AtLogOn -User $env:USERNAME
$settings = New-ScheduledTaskSettingsSet -StartWhenAvailable -DontStopOnIdleEnd -DontStopIfGoingOnBatteries -AllowStartIfOnBatteries -ExecutionTimeLimit (New-TimeSpan -Days 0)

Register-ScheduledTask -TaskName "UsageWatcherDaemon" `
    -Action $daemonAction -Trigger $logonTrigger -Settings $settings -Force | Out-Null
Register-ScheduledTask -TaskName "UsageWatcherTray" `
    -Action $trayAction   -Trigger $logonTrigger -Settings $settings -Force | Out-Null

Start-ScheduledTask -TaskName "UsageWatcherDaemon"
Start-ScheduledTask -TaskName "UsageWatcherTray"
OK "Registered daemon + tray as logon Scheduled Tasks"

# --- 7. Run once for an immediate seed ---------------------------------------
Step "Seeding initial snapshot…"
& node "$InstallDir\src\index.js" --once

# --- 8. Print iPhone QR ------------------------------------------------------
$scriptUrl = "https://raw.githubusercontent.com/jbss6888hn-tech/usage-watcher/main/ios-widget/UsageWidget.js"
$encoded   = [uri]::EscapeDataString($scriptUrl)
$payload   = "scriptable:///add?scriptURL=$encoded&gistId=$gistId"

Write-Host ""
Write-Host "=========================================================" -ForegroundColor Green
Write-Host "  ✓ Windows install complete. Now set up your iPhone:" -ForegroundColor Green
Write-Host "=========================================================" -ForegroundColor Green
Write-Host ""
Write-Host "  1. On iPhone install 'Scriptable' from the App Store."
Write-Host "  2. Open this URL on iPhone Safari (or scan with camera):"
Write-Host "       $payload" -ForegroundColor Yellow
Write-Host "  3. Tap 'Add' to import; tap ▶ Run, paste your GitHub PAT once."
Write-Host "  4. Long-press home/lock screen → + → Scriptable → add widget."
Write-Host ""

# Render a QR in the console if QRCoder module is available, otherwise fall back to a URL
$qrModule = Get-Module -ListAvailable -Name QRCodeGenerator | Select-Object -First 1
if (-not $qrModule) {
    try {
        Step "Installing QRCodeGenerator module for QR rendering…"
        Install-Module -Name QRCodeGenerator -Force -Scope CurrentUser -AcceptLicense -ErrorAction Stop | Out-Null
        $qrModule = Get-Module -ListAvailable -Name QRCodeGenerator | Select-Object -First 1
    } catch {
        Warn "Couldn't install QRCodeGenerator. Just open the URL above on your iPhone instead."
    }
}
if ($qrModule) {
    Import-Module QRCodeGenerator
    New-QRCodeText -Text $payload -OutputAsText
}

Write-Host ""
Write-Host "  Gist ID:     $gistId"
Write-Host "  Snapshot:    $ConfigDir\usage.json"
Write-Host "  Daemon log:  $ConfigDir\daemon.out.log"
Write-Host ""
Write-Host "  To stop the tray:    Unregister-ScheduledTask UsageWatcherTray"
Write-Host "  To stop the daemon:  Unregister-ScheduledTask UsageWatcherDaemon"
