#!/bin/bash
# Codex / Claude Usage Watcher — one-line installer for macOS
# Usage:  curl -fsSL https://raw.githubusercontent.com/jbss6888hn-tech/usage-watcher/main/install.sh | bash
set -euo pipefail

REPO_URL="${USAGE_WATCHER_REPO:-https://github.com/jbss6888hn-tech/usage-watcher.git}"
INSTALL_DIR="${USAGE_WATCHER_DIR:-$HOME/.usage-watcher}"
CONFIG_DIR="$HOME/.config/usage-watcher"
SWIFTBAR_DIR="$HOME/Library/Application Support/SwiftBar/Plugins"
PLIST_PATH="$HOME/Library/LaunchAgents/com.arrenwang.usage-watcher.plist"

BLUE="\033[1;34m"; GREEN="\033[1;32m"; YELLOW="\033[1;33m"; RED="\033[1;31m"; RESET="\033[0m"
step() { echo -e "${BLUE}▸ $*${RESET}"; }
ok()   { echo -e "${GREEN}✓ $*${RESET}"; }
warn() { echo -e "${YELLOW}! $*${RESET}"; }
die()  { echo -e "${RED}✗ $*${RESET}"; exit 1; }

[[ "$(uname -s)" == "Darwin" ]] || die "this installer is for macOS. Use install.ps1 on Windows."

# --- 1. Check / install Homebrew ---------------------------------------------
if ! command -v brew >/dev/null 2>&1; then
  step "Installing Homebrew (you may be asked for your password)…"
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi
BREW_PREFIX="$(brew --prefix)"
export PATH="$BREW_PREFIX/bin:$PATH"
ok "Homebrew at $BREW_PREFIX"

# --- 2. Node + git + jq + qrencode + gh --------------------------------------
needs_install=()
for pkg in node git jq qrencode gh; do
  if ! command -v "$pkg" >/dev/null 2>&1; then needs_install+=("$pkg"); fi
done
if [ ${#needs_install[@]} -gt 0 ]; then
  step "Installing: ${needs_install[*]}"
  brew install "${needs_install[@]}"
fi
ok "Node $(node --version), gh $(gh --version | head -1)"

# --- 3. SwiftBar (cask) -------------------------------------------------------
if ! brew list --cask swiftbar &>/dev/null; then
  step "Installing SwiftBar (menu bar host)…"
  brew install --cask swiftbar
fi
ok "SwiftBar installed"

# --- 4. GitHub auth (interactive) --------------------------------------------
if ! gh auth status -h github.com &>/dev/null; then
  step "GitHub login (your browser will open — pick 'gist' scope only)"
  gh auth login -h github.com -p https -s gist -w
fi
GH_TOKEN="$(gh auth token)"
[ -n "$GH_TOKEN" ] || die "gh auth token returned empty"
ok "GitHub authenticated"

# --- 5. Clone / pull repo ----------------------------------------------------
if [ -d "$INSTALL_DIR/.git" ]; then
  step "Updating $INSTALL_DIR…"
  git -C "$INSTALL_DIR" pull --ff-only
elif [ -d "$INSTALL_DIR" ]; then
  warn "$INSTALL_DIR exists but isn't a git repo. Backing up and re-cloning."
  mv "$INSTALL_DIR" "${INSTALL_DIR}.bak.$(date +%s)"
  git clone "$REPO_URL" "$INSTALL_DIR"
else
  step "Cloning $REPO_URL → $INSTALL_DIR…"
  git clone "$REPO_URL" "$INSTALL_DIR"
fi
ok "Repo at $INSTALL_DIR"

(cd "$INSTALL_DIR" && npm install --omit=dev --silent 2>/dev/null || npm install --omit=dev) >/dev/null
ok "npm deps installed (zero deps — fast)"

# --- 6. Auto-create or reuse private gist ------------------------------------
mkdir -p "$CONFIG_DIR" && chmod 700 "$CONFIG_DIR"

GIST_ID=""
if [ -f "$CONFIG_DIR/.env" ] && grep -q "^GIST_ID=" "$CONFIG_DIR/.env"; then
  GIST_ID="$(grep '^GIST_ID=' "$CONFIG_DIR/.env" | cut -d= -f2- | tr -d '"' )"
fi
if [ -z "$GIST_ID" ]; then
  step "Creating new private gist…"
  TMP_DIR="$(mktemp -d)"
  echo '{"placeholder": true}' > "$TMP_DIR/mac.json"
  echo '{"placeholder": true}' > "$TMP_DIR/win.json"
  GIST_URL="$(gh gist create "$TMP_DIR/mac.json" "$TMP_DIR/win.json" \
              --desc "Codex/Claude usage snapshot (private — by usage-watcher)" 2>&1 | tail -1)"
  rm -rf "$TMP_DIR"
  GIST_ID="${GIST_URL##*/}"
  ok "Gist created: $GIST_URL"
else
  ok "Reusing existing gist: $GIST_ID"
fi

# --- 7. Write .env (chmod 600) -----------------------------------------------
cat > "$CONFIG_DIR/.env" <<EOF
# Auto-generated by usage-watcher install.sh on $(date)
GIST_ID=$GIST_ID
GITHUB_TOKEN=$GH_TOKEN
HOST=mac
INTERVAL_SECONDS=60
EOF
chmod 600 "$CONFIG_DIR/.env"
ok ".env written to $CONFIG_DIR/.env"

# --- 8. Install launchd plist & load ----------------------------------------
NODE_BIN="$(command -v node)"
mkdir -p "$HOME/Library/LaunchAgents"
sed -e "s|__NODE_PATH__|$NODE_BIN|g" \
    -e "s|__INSTALL_DIR__|$INSTALL_DIR|g" \
    -e "s|__LOG_DIR__|$CONFIG_DIR|g" \
    "$INSTALL_DIR/install/mac.launchd.plist" > "$PLIST_PATH"

launchctl unload "$PLIST_PATH" 2>/dev/null || true
launchctl load "$PLIST_PATH"
ok "Daemon registered with launchd (auto-starts at login)"

# --- 9. SwiftBar plugin ------------------------------------------------------
mkdir -p "$SWIFTBAR_DIR"
cp "$INSTALL_DIR/swiftbar/usage.5s.sh" "$SWIFTBAR_DIR/usage.5s.sh"
chmod +x "$SWIFTBAR_DIR/usage.5s.sh"
ok "SwiftBar plugin installed at $SWIFTBAR_DIR/usage.5s.sh"
open -ga SwiftBar 2>/dev/null || true

# --- 10. Run once to seed the gist -------------------------------------------
step "Seeding initial snapshot…"
(cd "$INSTALL_DIR" && node src/index.js --once) || warn "first snapshot push had a hiccup — daemon will retry on schedule"

# --- 11. Print iPhone QR -----------------------------------------------------
SCRIPT_URL="https://raw.githubusercontent.com/jbss6888hn-tech/usage-watcher/main/ios-widget/UsageWidget.js"
QR_PAYLOAD="scriptable:///add?scriptURL=$(python3 -c "import urllib.parse,sys;print(urllib.parse.quote(sys.argv[1],safe=''))" "$SCRIPT_URL")&gistId=$GIST_ID"

echo
echo -e "${GREEN}=========================================================${RESET}"
echo -e "${GREEN}  ✓ Mac install complete. Now set up your iPhone:${RESET}"
echo -e "${GREEN}=========================================================${RESET}"
echo
echo "  1. On iPhone, install 'Scriptable' from the App Store (free)."
echo "  2. Scan the QR below with the iPhone camera (or open the URL)."
echo "  3. Scriptable will import the widget script."
echo "  4. Run it once → paste your GitHub PAT when asked (stored in iOS Keychain)."
echo "  5. Long-press home/lock screen → + → Scriptable → add widget."
echo
echo "  Your Gist ID:  $GIST_ID"
echo "  Script URL:    $SCRIPT_URL"
echo
qrencode -t ANSIUTF8 "$QR_PAYLOAD"
echo
echo "  (If the QR is hard to scan, manually open this URL on iPhone Safari:)"
echo "  $QR_PAYLOAD"
echo
echo -e "${GREEN}=========================================================${RESET}"
echo
echo "Snapshot file:  $CONFIG_DIR/usage.json"
echo "Daemon log:     $CONFIG_DIR/daemon.out.log"
echo "Plist:          $PLIST_PATH"
echo "To stop daemon: launchctl unload $PLIST_PATH"
